export const environment = {
  production: false,
  defaultauth: "fakebackend",
  //apiUrl: "https://solutiondigitale.sunuresto.com/",
  // apiUrl: "http://localhost:8081/",
//apiUrl:"https://solutiondigitale.sunuresto.com/",
apiUrl:"https://api.invodis.com/",
 //apiUrl:"http://localhost:8088/",
  //baseUrl: 'http://localhost:4200',
   // production: false,
    // apiURL: 'https://api.suntelecoms.com/SFD/api/',
    //apiURL: 'https://sfp.suntelecoms.com/api/',
    //apiURL: "http://localhost:8081/",
    batchApiURL: 'https://sfp.suntelecoms.com/batchapi/',
    apicomURL: 'https://api.suntelecoms.com/comapi/',
    //apiURL: 'https://solutiondigitale.sunuresto.com/',
    max: 100000,
    offset:0,
    maxTentative: 3,
    waitingTime: 1,
    sessionExpirationTime: 600,
    maxRatioMiniature : 1.500,
    minRatioMiniature : 1,
    ENCRYPT_SALT: "OdC&Xc30=8$HE`J1Tpq,GP*[[$qWBpA"
};
