import { MenuItem } from "./menu.model";

export const MENU: MenuItem[] = [
  {
    id: 1,
    label: "MENUITEMS.MENU.TEXT",
    isTitle: true,
  },
  {
    id: 2,
    label: "Dashboards",
    icon: "bx-home-circle",
    subItems: [
      {
        id: 3,
        label: "BaseLine PAR",
        link: "/dashboards/jobs",
        parentId: 2,
        icon: "bx-line-chart",
        permission: "DASHBOARD_BASELINE_VOIR",
      },
      {
        id: 4,
        label: "Mise en Oeuvre",
        link: "/dashboards/miseEnOeuvre",
        parentId: 2,
        icon: "bx-wrench",
        permission: "DASHBOARD_MISE_EN_OEUVRE_VOIR",
      },
    ],
  },
  {
    id: 5,
    label: "Projets",
    icon: "bx-briefcase-alt-2",
    subItems: [
      {
        id: 6,
        label: "Liste",
        icon: "bx-list-ul",
        link: "/projects/list",
        parentId: 5,
        permission: "PROJETS_VOIR",
      },
      {
        id: 7,
        label: "Normes",
        icon: "bx-book-open",
        link: "/projects/normes",
        parentId: 5,
        permission: "PROJETS_VOIR",
      },
    ],
  },
  {
    id: 8,
    label: "Maîtres d'ouvrages",
    icon: "bxs-buildings",
    subItems: [
      {
        id: 9,
        label: "Liste",
        icon: "bx-list-ul",
        link: "/maitrouvrages/list",
        parentId: 8,
        permission: "MAITRES_OUVRAGE_VOIR",
      },
    ],
  },
  {
    id: 10,
    label: "Parties Prenantes",
    icon: "bxs-group",
    subItems: [
      {
        id: 11,
        label: "Parties affectées",
        icon: "bxs-user-minus",
        link: "/pap/list",
        parentId: 10,
        // Pas de `permission` propre : la visibilité de ce nœud (lien + enfants) est déduite
        // de ses enfants, tous gated sur PAP_VOIR — voir l'algorithme de filtrage §6.2.
        subItems: [
          {
            id: 12,
            label: "Exploitants/Agricole",
            icon: "bxs-tree",
            link: "/pap/papAgricole",
            parentId: 11,
            permission: "PAP_VOIR",
          },
          {
            id: 13,
            label: "Place Affaires/Economiques",
            icon: "bxs-store",
            link: "/pap/papPlaceAffaire",
            parentId: 11,
            permission: "PAP_VOIR",
          },
          {
            id: 14,
            label: "Habitat",
            icon: "bxs-home",
            link: "/pap/papHabitat",
            parentId: 11,
            permission: "PAP_VOIR",
          },
        ],
      },
      {
        id: 15,
        label: "Parties intéréssées",
        icon: "bxs-user-check",
        parentId: 10,
        subItems: [
          {
            id: 16,
            label: "Liste",
            icon: "bx-list-ul",
            link: "/pip/",
            parentId: 15,
            permission: "PIP_VOIR",
          },
        ],
      },
    ],
  },
  {
    id: 17,
    label: "Consultants",
    icon: "bxs-id-card",
    subItems: [
      {
        id: 18,
        label: "Liste",
        icon: "bx-list-ul",
        link: "/consultant/chef-de-mission",
        parentId: 17,
        permission: "CONSULTANTS_VOIR",
      },
    ],
  },
  {
    id: 19,
    label: "Mise en œuvre du PAR",
    icon: "bx-task",
    subItems: [
      {
        id: 20,
        label: "Taches",
        icon: "bx-list-check",
        link: "/tasks/liste",
        parentId: 19,
        permission: "TACHES_VOIR",
      },
      {
        id: 21,
        label: "Entente de compensation",
        icon: "bx-handshake",
        link: "/ententeCompensation/list",
        parentId: 19,
        permission: "ENTENTE_COMPENSATION_VOIR",
      },
      {
        id: 22,
        label: "Mécanisme de gestion des plaintes",
        icon: "bxs-megaphone",
        parentId: 19,
        subItems: [
          {
            id: 23,
            label: "Phase d'Étude",
            icon: "bx-list-ul",
            link: "/plainte/list",
            parentId: 22,
            permission: "PLAINTES_VOIR",
          },
          {
            id: 24,
            label: "Phase de Mise en Œuvre",
            icon: "bx-list-ul",
            link: "/plainte/miseEnOeuvrePlainte",
            parentId: 22,
            permission: "PLAINTES_VOIR",
          },
        ],
      },
      {
        id: 25,
        label: "Accompagnement social",
        icon: "bxs-heart",
        parentId: 19,
        subItems: [
          {
            id: 26,
            label: "Liste",
            icon: "bx-list-ul",
            link: "/accompagnement/list",
            parentId: 25,
            permission: "ACCOMPAGNEMENT_SOCIAL_VOIR",
          },
        ],
      },
      {
        id: 27,
        label: "Restauration des moyens de subsistance",
        icon: "bx-recycle",
        parentId: 19,
        subItems: [
          {
            id: 28,
            label: "Liste",
            icon: "bx-list-ul",
            link: "/restauration/list",
            parentId: 27,
            permission: "RESTAURATION_SUBSISTANCE_VOIR",
          },
        ],
      },
      {
        id: 29,
        label: "Négociation et conciliation",
        icon: "bxs-conversation",
        parentId: 19,
        subItems: [
          {
            id: 30,
            label: "Liste",
            icon: "bx-list-ul",
            link: "/negociation/list",
            parentId: 29,
            permission: "NEGOCIATION_CONCILIATION_VOIR",
          },
        ],
      },
      {
        id: 31,
        label: "Paiement des compensations",
        icon: "bxs-credit-card",
        parentId: 19,
        subItems: [
          {
            id: 32,
            label: "Liste",
            icon: "bx-list-ul",
            link: "/paiement/list",
            parentId: 31,
            permission: "PAIEMENT_COMPENSATIONS_VOIR",
          },
        ],
      },
      {
        id: 33,
        label: "Engagements des parties prenantes",
        icon: "bxs-book-bookmark",
        parentId: 19,
        subItems: [
          {
            id: 34,
            label: "Liste",
            icon: "bx-list-ul",
            link: "/engagements/list",
            parentId: 33,
            permission: "ENGAGEMENTS_PARTIES_VOIR",
          },
        ],
      },
    ],
  },
  {
    id: 35,
    label: "Gestion des documents",
    icon: "bxs-folder",
    subItems: [
      {
        id: 36,
        label: "Documents",
        icon: "bxs-file",
        link: "/dossiers",
        parentId: 35,
        permission: "DOCUMENTS_VOIR",
      },
      {
        id: 37,
        label: "Catégories documents",
        icon: "bxs-category",
        link: "/catégorie-dossier",
        parentId: 35,
        permission: "CATEGORIES_DOCUMENTS_VOIR",
      },
    ],
  },
  {
    id: 38,
    label: "Élaboration du PAR",
    icon: "bxs-detail",
    subItems: [
      {
        id: 39,
        label: "Liste",
        icon: "bx-list-ul",
        link: "/rencontres",
        parentId: 38,
        permission: "ELABORATION_PAR_VOIR",
      },
    ],
  },
  {
    id: 40,
    label: "Géolocalisation",
    icon: "bxs-map",
    subItems: [
      {
        id: 41,
        label: "Quartiers",
        icon: "bx-buildings",
        link: "/geolocalisation/quartiers",
        parentId: 40,
        permission: "GEOLOCALISATION_QUARTIERS_VOIR",
      },
      {
        id: 42,
        label: "Points de repère",
        icon: "bx-map-pin",
        link: "/geolocalisation/points-de-repere",
        parentId: 40,
        permission: "GEOLOCALISATION_POINTS_VOIR",
      },
    ],
  },
  {
    id: 43,
    label: "Paramétrage",
    isTitle: true,
    // Titre = parent réel d'Administration (voir GESTION_PERMISSIONS_DOC.md §6.3) :
    // masqué automatiquement si aucun enfant n'est visible, plus besoin de rôle en dur ici.
    subItems: [
      {
        id: 44,
        label: "Administration",
        icon: "bxs-cog",
        parentId: 43,
        subItems: [
          {
            id: 45,
            label: "Utilisateurs",
            icon: "bxs-user-detail",
            link: "/utilisateurs",
            parentId: 44,
            permission: "UTILISATEURS_VOIR",
          },
          {
            id: 46,
            label: "Rôles",
            icon: "bxs-shield",
            link: "/roles",
            parentId: 44,
            permission: "ROLES_VOIR",
          },
          {
            id: 47,
            label: "Fonctions",
            icon: "bxs-briefcase",
            link: "/fonctions",
            parentId: 44,
            permission: "FONCTIONS_VOIR",
          },
          {
            id: 48,
            label: "Catégories utilisateurs",
            icon: "bxs-label",
            link: "/categories",
            parentId: 44,
            permission: "CATEGORIES_UTILISATEURS_VOIR",
          },
          {
            id: 49,
            label: "Journal d'audit",
            icon: "bxs-history",
            link: "/audit",
            parentId: 44,
            permission: "AUDIT_VOIR",
          },
        ],
      },
    ],
  },
];
